function BrainSoundLab
%BRAINSOUNDLAB BrainSoundLab entry point

% Open main figure
figure('Name', 'BrainSoundLab', 'NumberTitle', 'off', 'DockControls', 'off', ...
    'MenuBar', 'none', 'Tag', 'BrainSoundLab', 'Position', [100, 50, 1500, 900], ...
    'ResizeFcn', @ResizeFcn, ...
    'CloseRequestFcn', @CloseRequestFcn);

% Initialize BrainSoundLabData class and create a menu
BSL = BrainSoundLabData;
guidata(gcf, BSL);

% CreateDebugMenu(BSL);

% Load panels from the '+panel' folder
panel_files = what(['BrainSoundLab' filesep '+panel']);
[~, panel_names] = cellfun(@fileparts, panel_files.m, 'UniformOutput', false);
for k = 1:length(panel_names)
    panel_name = panel_names{k};
    BSL.panels.(panel_name) = panel.(panel_name);
end

% Get tags of the initially open panels and make them visible
tags = zeros(1, length(BSL.defaultPanels));
for k = 1:length(BSL.defaultPanels)
    tags(k) = BSL.panels.(BSL.defaultPanels{k});
end
BSL.openPanels = tags;
set(BSL.openPanels, 'Visible', 'on');

end

% CreateMenu function -----------------------------------------------------
function CreateDebugMenu(BSL)
% Panels
panelsMenu = uimenu(gcf, 'Label', 'Debug');
uimenu(panelsMenu, 'Label', 'Experiment', 'Checked', 'on', ...
    'Tag', 'Experiment', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'Information', 'Checked', 'on', ...
    'Tag', 'Information', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'Electrode', 'Checked', 'on', ...
    'Tag', 'Electrode', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'Raster', 'Checked', 'on', ...
    'Tag', 'Raster', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'PSTH', 'Checked', 'on', ...
    'Tag', 'PSTH', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'TRF', ...
    'Tag', 'TRF', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'TRF laser', ...
    'Tag', 'TRF_Laser', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'TRF IsodB2xMix_WN', ...
    'Tag', 'TRF_IsodB2xMix_WN', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'All Channels TRF 16', ...
    'Tag', 'AllChTRF_16', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'All Channels TRF 32', ...
    'Tag', 'AllChTRF_32', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'Tuning Curves', ...
    'Tag', 'TuningCurves', ...
    'Callback', @BSL.showHidePanel);
uimenu(panelsMenu, 'Label', 'Selectivity Indexes', ...
    'Tag', 'SelectivityInd', ...
    'Callback', @BSL.showHidePanel);
end

% BrainSoundLab figure callback functions ---------------------------------
function ResizeFcn(hObject, eventdata)
BSL = guidata(gcf);
if isempty(BSL); return; end % Pass the initial ResizeFcn call upon figure creation
BSL.updatePanelPosition();
end

function CloseRequestFcn(hObject, eventdata)
switch questdlg('Do you want to close the application?', ...
        'BrainSoundLab', 'Yes', 'No', 'No')
    case 'Yes'
        delete(gcf);
    otherwise
        return
end
end

