function p = AllChTRF_16
ph = 385; % panel height
pTitle = 'All Channels TRF';
pTag = 'AllChTRF_16';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 540 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [497 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [517 ph-30 20 16]);
% Panel components --------------------------------------------------------
width = 4;
height = 4;
for k = 1:width
    for l = 1:height
        axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
            'Box', 'on', 'FontSize', 9, 'XTickLabel', '', 'YTickLabel', '', ...
            'Tag', ['ax_allChTRF_' num2str(height*(k-1)+l)], ...
            'Position', [15+130*(k-1), ph-30-85*l, 120, 75]);
    end
end

