function p = DiscriTest
ph = 365; % panel height
pTitle = 'Discrimination Test';
pTag = 'DiscriTest';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 1000 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [957 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [977 ph-30 20 16]);
% Panel components --------------------------------------------------------
% Hit Rate 
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_HitRate', ...
    'Position', [60, ph-150, 200, 125]);
xlabel('Time, s');
ylabel('Hit rate');
% False Alarm Rate
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_FARate', ...
    'Position', [320, ph-150, 200, 125]);
xlabel('Time, s');
ylabel('FA rate');
% % Empty
% axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
%     'Box', 'on', ...
%     'FontSize', 9, ...
%     'Tag', '', ...
%     'Position', [580, ph-150, 200, 125]);
% xlabel('Frequency, kHz');
% ylabel('Rate, spikes/s');
% Discriminability index d'
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_dprime', ...
    'Position', [60, ph-320, 200, 125]);
xlabel('Time, s');
ylabel('Dprime');
% Correct Response
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_correctresponse', ...
    'Position', [320, ph-320, 200, 125]);
xlabel('Time, s');
ylabel('Correct response (%)');
% Reaction Time
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_reaxtime', ...
    'Position', [580, ph-320, 200, 125]);
xlabel('Time,s');
ylabel('Reaction Time, s');

