function p = DT_sequence % Deviant tone sequence analysis
ph = 220; % panel height
pTitle = 'DT sequence';
pTag = 'DT_sequence';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 1000 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [957 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [977 ph-30 20 16]);
% Panel components --------------------------------------------------------
% DT analysis axes
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_dt_sequence', ...
    'Position', [60, 45, 720, 150]);
xlabel('Number of preceding standard tones');
ylabel('Spike number');

