function p = PSTH
ph = 220; % panel height
pTitle = 'PSTH';
pTag = 'PSTH';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 1000 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [957 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [977 ph-30 20 16]);
% Panel components --------------------------------------------------------
% PSTH axes
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_psth', ...
    'Position', [60, 45, 720, 150]);
xlabel('Time, s');
ylabel('Spike count');
% Fix spike count axes limits
uicontrol(p, 'Style', 'checkbox', 'HorizontalAlignment', 'left', ...
    'String', 'Fix spike count axes limits', ...
    'Enable', 'off', ...
    'Tag', 'fixSpikeCount_psth', ...
    'Value', BSL.fixLim_psth, ...
    'Callback', @(h,ed) Callback_fixLimit(h, BSL), ...
    'Position', [810 ph-50 150 20]);
% --- fixed value
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'fixed max value:', ...
    'Position', [820 ph-71 150 14]);
if BSL.fixLim_psth; str = 'on';
else str = 'off'; end
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Enable', str, ...
    'Tag', 'e_fixedMaxVal_psth', ...
    'Callback', @(h,ed) Callback_fixedVal(h, BSL), ...
    'Position', [920 ph-75 51 22]);
% Number of bins
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'Number of bins:', ...
    'Position', [810 ph-104 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'String', BSL.nBins_psth, ...
    'Enable', 'off', ...
    'Tag', 'e_nBins_psth', ...
    'Callback', @(h,ed) Callback_nBins(h, BSL), ...
    'Position', [920 ph-108 51 22]);
% Number of std. dev.
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'Number of std. dev.:', ...
    'Position', [810 ph-137 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'String', BSL.nStdDev_psth, ...
    'Enable', 'off', ...
    'Tag', 'e_nStdDev_psth', ...
    'Callback', @(h,ed) Callback_nStdDev(h, BSL), ...
    'Position', [920 ph-141 51 22]);

function Callback_fixLimit(hObject, BSL)
if get(hObject, 'Value') == get(hObject, 'Max')
    BSL.fixLim_psth = true;
    set(findobj('Tag', 'e_fixedMaxVal_psth'), 'Enable', 'on');
else
    BSL.fixLim_psth = false;
    set(findobj('Tag', 'e_fixedMaxVal_psth'), 'Enable', 'off');
    set(findobj('Tag', 'ax_psth'), 'YLimMode', 'auto');
    lim = get(findobj('Tag', 'ax_psth'), 'YLim');
    BSL.fixedMaxVal_psth = lim(2);
    display.updateProcArea();
end

function Callback_fixedVal(hObject, BSL)
val = sscanf(get(hObject, 'String'), '%f', 1);
if isempty(val)
    set(hObject, 'String', BSL.fixedMaxVal_psth);
    errordlg('fixedMaxVal_psth must be a number', 'Error');
    return
end
BSL.fixedMaxVal_psth = val;
ylim(findobj('Tag', 'ax_psth'), [0, val]);
display.updateProcArea();

function Callback_nBins(hObject, BSL)
val = sscanf(get(hObject, 'String'), '%f', 1);
if isempty(val)
    set(hObject, 'String', BSL.nBins_psth);
    errordlg('nBins_psth must be a number', 'Error');
    return
end
BSL.nBins_psth = val;
display.PSTH();

function Callback_nStdDev(hObject, BSL)
val = sscanf(get(hObject, 'String'), '%f', 1);
if isempty(val)
    set(hObject, 'String', BSL.nStdDev_psth);
    errordlg('nStdDev_psth must be a number', 'Error');
    return
end
BSL.nStdDev_psth = val;

BSL.block.processData('autoProcRange');

