function p = TRF % Tonal receptive field
ph = 240; % panel height
pTitle = 'TRF';
pTag = 'TRF';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 1000 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [957 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [977 ph-30 20 16]);
% Panel components --------------------------------------------------------
% TRF axes
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_trf', ...
    'Position', [60, 45, 200, 125]);
xlabel('Stimulus');
ylabel('Stimulus');
% Filtered TRF axes
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_trf_filt', ...
    'Position', [320, 45, 200, 125]);
xlabel('Stimulus');
ylabel('Stimulus');
% Clean TRF axes
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_trf_clean', ...
    'Position', [580, 45, 200, 125]);
xlabel('Stimulus');
ylabel('Stimulus');
% Local colormap scaling
uicontrol(p, 'Style', 'checkbox', 'HorizontalAlignment', 'left', ...
    'String', 'Local colormap scaling', ...
    'Tag', 'cb_localColorScale_trf', ...
    'Callback', @Callback_autoscaleColormap, ...
    'Position', [810 ph-50 150 20]);
% Median filtering iter.
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'Median filtering iter.:', ...
    'Position', [810 ph-79 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Tag', 'e_iterations_trf', ...
    'String', 1, ...
    'Callback', @Callback_iterations, ...
    'Position', [920 ph-83 51 22]);
% --- size
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'size:', ...
    'Position', [820 ph-102 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Tag', 'e_medFiltX_trf', ...
    'String', 4, ...
    'Callback', @Callback_medFiltSize, ...
    'Position', [870 ph-106 51 22]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Tag', 'e_medFiltY_trf', ...
    'String', 4, ...
    'Callback', @Callback_medFiltSize, ...
    'Position', [920 ph-106 51 22]);
% Clean with peak amplitude
uicontrol(p, 'Style', 'checkbox', 'HorizontalAlignment', 'left', ...
    'String', 'Clean with the peak amplitude', ...
    'Tag', 'cb_cleanWithPeakAmpl_trf', ...
    'Value', 0, ...
    'Callback', @Callback_cleanWithPeakAmpl, ...
    'Position', [810 ph-139 170 20]);
% --- peak amplitude portion
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'peak ampl. portion:', ...
    'Position', [820 ph-158 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Enable', 'off', ...
    'Tag', 'e_peakAmplPort_trf', ...
    'String', 0.2, ...
    'Callback', @Callback_peakAmplPort, ...
    'Position', [920 ph-162 51 22]);

function Callback_autoscaleColormap(hObject, eventdata)
display.TRF();

function Callback_iterations(hObject, eventdata)
process.analyseTRF();
display.TRF();

function Callback_medFiltSize(hObject, eventdata)
process.analyseTRF();
display.TRF();

function Callback_cleanWithPeakAmpl(hObject, eventdata)
if get(hObject, 'Value') == 1
    set(findobj('Tag', 'e_peakAmplPort_fra'), 'Enable', 'on');
else
    set(findobj('Tag', 'e_peakAmplPort_fra'), 'Enable', 'off');
end
process.analyseTRF();
display.TRF();

function Callback_peakAmplPort(hObject, eventdata)
process.analyseTRF();
display.TRF();

