function p = TRF_IsodB2xMix
ph = 365; % panel height
pTitle = 'TRF IsodB2xMix';
pTag = 'TRF_IsodB2xMix';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 1000 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [957 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [977 ph-30 20 16]);
% Panel components --------------------------------------------------------
% Control trials
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_control_isodB2xMix', ...
    'Position', [60, ph-150, 200, 125]);
xlabel('Frequency, kHz');
ylabel('Control rate, spikes/s');
% Laser trials
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_laser_isodB2xMix', ...
    'Position', [320, ph-150, 200, 125]);
xlabel('Frequency, kHz');
ylabel('Laser rate, spikes/s');
%empty
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_0dB_isodB2xMix', ...
    'Position', [60, ph-320, 200, 125]);
xlabel('Frequency, kHz');
ylabel('0dB rate, spikes/s');


