function p = TRF_Laser % Tonal receptive field (laser compare)
ph = 365; % panel height
pTitle = 'TRF Laser';
pTag = 'TRF_Laser';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 1000 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [957 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [977 ph-30 20 16]);
% Panel components --------------------------------------------------------
% TRF axes 1
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_trf1_TRFlaser', ...
    'Position', [60, ph-150, 200, 125]);
xlabel('Stimulus');
ylabel('Stimulus');
% Clean TRF axes 1
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_clean1_TRFlaser', ...
    'Position', [320, ph-150, 200, 125]);
xlabel('Stimulus');
ylabel('Stimulus');
% TRF axes 2
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_trf2_TRFlaser', ...
    'Position', [60, ph-320, 200, 125]);
xlabel('Stimulus');
ylabel('Stimulus');
% Clean TRF axes 2
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_clean2_TRFlaser', ...
    'Position', [320, ph-320, 200, 125]);
xlabel('Stimulus');
ylabel('Stimulus');
% Compare TRF sections
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_compare_TRFlaser', ...
    'Position', [580, ph-255, 200, 125]);
xlabel('Frequency, kHz');
ylabel('Activity rate, spikes/s');
% Laser group labels
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', [char(8592) ' Control'], ...
    'Position', [550 ph-100 150 14]);
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'FontSize', 10, ...
    'String', [char(8592) ' Laser'], ...
    'Position', [550 ph-320 150 14]);
% Local colormap scaling
uicontrol(p, 'Style', 'checkbox', 'HorizontalAlignment', 'left', ...
    'String', 'Local colormap scaling', ...
    'Tag', 'cb_localColorScale_TRFlaser', ...
    'Callback', @Callback_autoscaleColormap, ...
    'Position', [810 ph-50 150 20]);
% Median filtering iter.
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'Median filtering iter.:', ...
    'Position', [810 ph-79 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Tag', 'e_iterations_TRFlaser', ...
    'String', 1, ...
    'Callback', @Callback_iterations, ...
    'Position', [920 ph-83 51 22]);
% --- size
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'size:', ...
    'Position', [820 ph-102 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Tag', 'e_medFiltX_TRFlaser', ...
    'String', 4, ...
    'Callback', @Callback_medFiltSize, ...
    'Position', [870 ph-106 51 22]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Tag', 'e_medFiltY_TRFlaser', ...
    'String', 4, ...
    'Callback', @Callback_medFiltSize, ...
    'Position', [920 ph-106 51 22]);
% Clean with peak amplitude
uicontrol(p, 'Style', 'checkbox', 'HorizontalAlignment', 'left', ...
    'String', 'Clean with the peak amplitude', ...
    'Tag', 'cb_cleanWithPeakAmpl_TRFlaser', ...
    'Value', 0, ...
    'Callback', @Callback_cleanWithPeakAmpl, ...
    'Position', [810 ph-139 170 20]);
% --- peak amplitude portion
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'peak ampl. portion:', ...
    'Position', [820 ph-158 150 14]);
uicontrol(p, 'Style', 'edit', 'HorizontalAlignment', 'left', ...
    'Enable', 'off', ...
    'Tag', 'e_peakAmplPort_TRFlaser', ...
    'String', 0.2, ...
    'Callback', @Callback_peakAmplPort, ...
    'Position', [920 ph-162 51 22]);
% Section TRF at
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'Section TRF at:', ...
    'Position', [810 ph-191 170 14]);
uicontrol(p, 'Style', 'text', 'HorizontalAlignment', 'left', ...
    'String', 'dB', ...
    'Position', [973 ph-191 150 14]);
uicontrol(p, 'Style', 'popupmenu', 'HorizontalAlignment', 'left', ...
    'Tag', 'pm_sectionTRF_TRFlaser', ...
    'String', {' '}, ...
    'Callback', @Callback_sectionTRF, ...
    'Position', [920 ph-195 51 22]);

function Callback_autoscaleColormap(hObject, eventdata)
display.TRF_Laser();

function Callback_iterations(hObject, eventdata)
process.analyseTRF();
display.TRF_Laser();

function Callback_medFiltSize(hObject, eventdata)
process.analyseTRF();
display.TRF_Laser();

function Callback_cleanWithPeakAmpl(hObject, eventdata)
if get(hObject, 'Value') == 1
    set(findobj('Tag', 'e_peakAmplPort_TRFlaser'), 'Enable', 'on');
else
    set(findobj('Tag', 'e_peakAmplPort_TRFlaser'), 'Enable', 'off');
end
process.analyseTRF();
display.TRF_Laser();

function Callback_peakAmplPort(hObject, eventdata)
process.analyseTRF();
display.TRF_Laser();

function Callback_sectionTRF(hObject, eventdata)
display.TRF_Laser();

