function p = TuningCurves
ph = 720; % panel height
pTitle = 'Tuning Curves';
pTag = 'TuningCurves';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 540 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [497 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [517 ph-30 20 16]);
% Panel components --------------------------------------------------------
% Spike number average
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_spikeNumAvg', ...
    'Position', [60, ph-165, 200, 125]);
xlabel('Stimulus');
ylabel('Avg spike number');
% Spike number
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_spikeNum', ...
    'Position', [320, ph-165, 200, 125]);
xlabel('Stimulus');
ylabel('Spike number');
% Spike rate average
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_spikeRateAvg', ...
    'Position', [60, ph-335, 200, 125]);
xlabel('Stimulus');
ylabel('Avg spike rate, spikes/s');
% Spike rate
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_spikeRate', ...
    'Position', [320, ph-335, 200, 125]);
xlabel('Stimulus');
ylabel('Spike rate, spikes/s');
% Peak latency average
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_peakLatencyAvg', ...
    'Position', [60, ph-505, 200, 125]);
xlabel('Stimulus');
ylabel('Avg peak latency, s');
% Peak amplitude average
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_peakAmpAvg', ...
    'Position', [320, ph-505, 200, 125]);
xlabel('Stimulus');
ylabel('Avg peak amp, spikes/s');
% Onset latency
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_onsetLatency', ...
    'Position', [60, ph-675, 200, 125]);
xlabel('Stimulus');
ylabel('Onset latency, s');
% Spont activity
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_spontActivity', ...
    'Position', [320, ph-675, 200, 125]);
xlabel('Stimulus');
ylabel('Spont activity, spikes/s');

