function p = TuningCurves_Laser
ph = 365; % panel height
pTitle = 'Tuning Curves Laser';
pTag = 'TuningCurves_Laser';
% Panel and hide button
p = uipanel(gcf, 'Units', 'pixels', 'FontWeight', 'bold', 'Visible', 'off', ...
    'BorderType', 'line', 'HighlightColor', [0.5 0.5 0.5], ...
    'Title', pTitle, ...
    'Tag', pTag, ...
    'Position', [0 0 1000 ph]);
BSL = guidata(gcf);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', char(9645), 'FontWeight', 'bold', 'FontSize', 12, ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.popPanel(p), ...
    'Position', [957 ph-30 21 16]);
uicontrol(p, 'Style', 'pushbutton', ...
    'String', 'x', ...
    'HitTest', 'off', ...
    'Callback', @(h,ed) BSL.hidePanel(pTag), ...
    'Position', [977 ph-30 20 16]);
% Panel components --------------------------------------------------------
% DSI with spont activity
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_dsi_n', ...
    'Position', [60, ph-150, 200, 125]);
xlabel('Absolute rate, |oct/s|');
ylabel('DSI w spont');
ylim([-1, 1]);
% DSI without spont
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_dsi_r', ...
    'Position', [60, ph-320, 200, 125]);
xlabel('Absolute rate, |oct/s|');
ylabel('DSI w/o spont');
ylim([-1, 1]);
% LSI with spont activity
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_lsi_n', ...
    'Position', [320, ph-150, 200, 125]);
xlabel('Rate, oct/s');
ylabel('LSI w spont');
ylim([0, 1]);
% LSI without spont activity
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_lsi_r', ...
    'Position', [320, ph-320, 200, 125]);
xlabel('Rate, oct/s');
ylabel('LSI w/o spont');
ylim([0, 1]);
% RSI spike number
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_rsi_n', ...
    'Position', [580, ph-150, 200, 125]);
xlabel('Direction');
ylabel('RSI, number');
ylim([0, 1]);
% RSI rate
axes('Parent', p, 'Units', 'pixels', 'NextPlot', 'replacechildren', ...
    'Box', 'on', ...
    'FontSize', 9, ...
    'Tag', 'ax_rsi_r', ...
    'Position', [580, ph-320, 200, 125]);
xlabel('Direction');
ylabel('RSI, rate');
ylim([0, 1]);

